service: banking-account

variablesResolutionMode: 20210326

frameworkVersion: "2"

plugins:
  - serverless-webpack # must be the first of the list
  - serverless-dynamodb-local
  - serverless-offline # must be the last of the list


provider:
  name: aws
  runtime: nodejs14.x
  environment: 
    accountsTableName: Account
    operationsTableName: Operations

functions:
  postDeposit:
    handler: ./src/apps/operations/handlers/postDeposit.main
    events:
    - http:
        path: /accounts/{accountId}/deposit
        method: post
  postWithdrawal:
    handler: ./src/apps/operations/handlers/postWithdrawal.main
    events:
    - http:
        path: /accounts/{accountId}/withdrawal
        method: post
  getOperations:
    handler: ./src/apps/operations/handlers/getOperations.main
    events:
    - http:
        path: /accounts/{accountId}/operations
        method: get

resources:
  Resources:
    AccountTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.accountsTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    OperationsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.operationsTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: _accountId
            AttributeType: S
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
        - IndexName: accountIndex
          KeySchema:
            - AttributeName: _accountId
              KeyType: HASH
            - AttributeName: date
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES


custom:
  webpack:
    webpackConfig: ./webpack.config.js
    packager: yarn # or npm
    includeModules: true

  dynamodb:
    stages:
      - local
    start:
      docker: true
      image: dynamodb-local
      port: 8000
      inMemory: true
      noStart: true
      migrate: true
      seed: true
    seed:
      default:
        sources:
        - table: ${self:provider.environment.accountsTableName}
          sources: [./seeds/account.json]
