service: starter

variablesResolutionMode: 20210326

frameworkVersion: "2"

plugins:
  - serverless-webpack # must be the first of the list
  - serverless-dynamodb-local
  - serverless-offline # must be the last of the list
  - serverless-plugin-offline-dynamodb-stream


provider:
  name: aws
  runtime: nodejs16.x

functions:
  create:
    handler: ./src/apps/games/handlers/createGame.main
    events:
    - http:
        path: games
        method: post

resources:
  Resources:
    AccountTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.accountsTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    OperationsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.operationsTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: _accountId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
        - IndexName: accountIndex
          KeySchema:
            - AttributeName: _accountId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES


custom:
  webpack:
    webpackConfig: ./webpack.config.js
    packager: yarn # or npm
    includeModules: true

  dynamodb:
    stages:
      - local
    start:
      docker: true
      image: dynamodb-local
      port: 8000
      inMemory: true
      noStart: true
      migrate: true